### ISSUE TITLE
Files not extracted?

### ISSUE THREAD

**Issue by badmotorfinger** [barberd/macmfsextract#1]
I found your python script online and thought you might be able to help me out. I am trying to extract the contents of .image files within linux. Although the script executes, I don't actually see file contents being output. The file I'm trying this out on is attached.

[SIMCITY.image.zip](https://github.com/barberd/macmfsextract/files/11070321/SIMCITY.image.zip)

The output I'm getting is:

Volume Name: b'SIM CITY'
Volume Create Datestamp: 2694
Volume Modify Datestamp: 2809

The place where the script is breaking out is ` #we're past the end of the file directory, exit out`

However, I don't see any files.

Would appreciate some help. Thank you.

**Comment by barberd** [comment]
Hi there! This is an HFS image, not an MFS image, so my script doesn't know how to read it. HFS was adopted by Apple in September 1985; see https://en.wikipedia.org/wiki/Hierarchical_File_System_(Apple).

**Comment by barberd** [comment]
Hi there! This is an HFS image, not an MFS image, so my script doesn't know how to read it. HFS was adopted by Apple in September 1985; see https://en.wikipedia.org/wiki/Hierarchical_File_System_(Apple).

The good news is that Linux can read HFS already. Try 'sudo mount SIMCITY.image /mnt' and you should find it under /mnt. There is also a set of command line utilities called hfsutils (https://www.mars.org/home/rob/proj/hfs/) that you can probably install just by running 'apt install hfsutils' or 'yum install hfsutils' depending upon your distribution.

That being said, this looks like a pretty standard copy of SimCity; you can get it at https://macintoshgarden.org/games/simcity too.

**Comment by barberd** [comment]
Also next time you can run 'file SIMCITY.image' and see what type of image it is. 

>file SIMCITY.image
SIMCITY.image: Macintosh HFS data block size: 512, number of blocks: 1594, volume name: SIM CITY

**Comment by badmotorfinger** [comment]
Thank you so much for your help and responses.

I never knew about the "file" command in linux. You've helped me a great deal with my problem, will go with the mount option.

Cheers
